### ISSUE TITLE
Conflict-free solution is needed

### ISSUE THREAD

**Issue by larrycinnabar** [EDLadder/Hats-For-Parties#2]
Hey.

One of the requirements of the problem was:

> 5. Solution should be conflict-free when two or more parties are being started almost at the same time, they must not rent the same hats. Consider, that the running application will be run as a scalable microservice (so multiple binaries of it can run at the same time)

In the current code, it won't work. Imagine, you have called `CreateParty()` at exact one millisecond (almost the same moment). Then, both requests can "reserve" the same hats, that's impossible. This is a race condition, that needs to be solved.

Hint: MongoDb has built-in solutions, that are very easy to use.

**Comment by EDLadder** [comment]
Yeap, you are right. Let me check this.
