### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by larrycinnabar** [EDLadder/Hats-For-Parties#4]
Github doesn't allow to comment on commits, and as no Pull Request is created, I'll do Code Review here manually, specifying links to the code:

#### (Just some notes, related to Golang and Mongo specifically)

1.
https://github.com/EDLadder/Hats-For-Parties/blob/f51d4328d7c80da5adf764a1431dd1ba209f17bb/parties-service/controllers/partyController.go#L38

Any reason, you manually do iteration? mongo golang client has built-in iterator, that simplifies this piece of code.

2.
https://github.com/EDLadder/Hats-For-Parties/blob/f51d4328d7c80da5adf764a1431dd1ba209f17bb/parties-service/controllers/partyController.go#L42

(this comment will go away when you fix previous one, but anyway): Do you actually want to just log.Fatal here? maybe a nicer error for user?

3.
https://github.com/EDLadder/Hats-For-Parties/blob/f51d4328d7c80da5adf764a1431dd1ba209f17bb/parties-service/controllers/partyController.go#L52

Please, don't mix json unmarshalling (via library) and manual marshalling via string concatenation. Create a model (struct) for your Parties envelope, and just marshal it altogether

4.
https://github.com/EDLadder/Hats-For-Parties/blob/f51d4328d7c80da5adf764a1431dd1ba209f17bb/parties-service/controllers/partyController.go#L27

Any ideas how to make client not to be a global shared variable? (maybe a controller's field, etc)

5.
https://github.com/EDLadder/Hats-For-Parties/blob/f51d4328d7c80da5adf764a1431dd1ba209f17bb/parties-service/controllers/partyController.go#L84
Why omitting error here? it's possible that config was invalid, and then we need to fail with internal error as well

6.
https://github.com/EDLadder/Hats-For-Parties/blob/f51d4328d7c80da5adf764a1431dd1ba209f17bb/parties-service/controllers/partyController.go#L103

You may be interesting to look into `UseSession` function, that will simplify this piece of code drastically

7.
https://github.com/EDLadder/Hats-For-Parties/blob/f51d4328d7c80da5adf764a1431dd1ba209f17bb/parties-service/controllers/partyController.go#L174
Same thing here: make please a model for this envelope, so you don't do manual marshalling via json string concatenation

8.
https://github.com/EDLadder/Hats-For-Parties/blob/f51d4328d7c80da5adf764a1431dd1ba209f17bb/parties-service/config/config.go#L14

Do you actually want to fatal when config is written bad? Let this function just return an error + the value, so the calling side will decide what to do if error happens (maybe it can fallback to some other config value, etc)

9.
https://github.com/EDLadder/Hats-For-Parties/blob/f51d4328d7c80da5adf764a1431dd1ba209f17bb/parties-service/validators/validators.go#L18

Similar thing: no panic for such a reason. You return an error (that you could not perform validation), and the calling side will decide how to handle this kind of failure

10.
https://github.com/EDLadder/Hats-For-Parties/blob/f51d4328d7c80da5adf764a1431dd1ba209f17bb/parties-service/models/hat.go#L10

Better to use native go types, like `time.Time` (or pointered *time.Time). But not some database-specific type (as the same model can be used for other databases as well)

11.
https://github.com/EDLadder/Hats-For-Parties/blob/f51d4328d7c80da5adf764a1431dd1ba209f17bb/parties-service/db/db.go#L24
2 consecutive fatals don't make any sense. First fatal will just exit the application (no code is executed after)

## And a major issue:
Problem is, that solution is still not concurrent. You used transactions, but transaction locks documents, but not the collection. If you do "CreateParty" very close enough, it will reserve the SAME hats to different parties.

You're tested it here:
https://github.com/EDLadder/Hats-For-Parties/blob/f51d4328d7c80da5adf764a1431dd1ba209f17bb/parties-service/controllers/partyController.go#L128

But, your sleep should be AFTER find - then you catch your main issue (if you add a sleep between Find and Update). Hint: in mongo there are functions that can make your code easier AND solve the issue.

**Comment by EDLadder** [comment]
I tried to solve everything you wrote. maybe I didn't understand everything.
On point:
`5. Solution should be conflict-free when two or more parties are being started almost at the same time, they must not rent the same hats. Consider, that the running application will be run as a scalable microservice (so multiple binaries of it can run at the same time)`
I did not find a solution.

**Comment by EDLadder** [comment]
I can’t use [FindOneAndUpdate](https://pkg.go.dev/go.mongodb.org/mongo-driver@v1.10.0/mongo#Collection.FindOneAndUpdate) because i can set limit(Or i don’t find how to do that).
[UpdateMany](https://pkg.go.dev/go.mongodb.org/mongo-driver@v1.10.0/mongo#Collection.UpdateMany) same thing.
I think that in this case(1. Create Party 2. Update x Hats) it is necessary to use the transaction.
